name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort mypy
    - name: Analysing the code with pylint
      run: |
        black `ls -R|grep .py$|xargs`
        flake8 `ls -R|grep .py$|xargs`
        isort `ls -R|grep .py$|xargs`
        mypy `ls -R|grep .py$|xargs`
        
